### ISSUE TITLE
Errors on multiple rails methods when using tml as i18n bakend

### ISSUE THREAD

**Issue by thatguysimon** [translationexchange/tml-rails#2]
Hey there,
I've been trying to set Tml to work as my i18n backend as instructed in your documentation.

``` ruby
I18n.backend = I18n::Backend::Tml.new
```

Unfortunately, I've encountered the following 3 errors so far:
1) When using the rails method **number_with_delimiter** as part of a variable in a call to a translation:

``` ruby
<%= t("hello", :number => number_with_delimiter(5)) %>
```

 I get the error:

```
undefined method `gsub' for 3:Fixnum
```

2) When using the rails method **parameterize** 

``` ruby
<%= "Hello there".parameterize %>
```

I get the error:

```
undefined method `html_safe' for {}:Hash
```

3) And the same error when using the method **to_sentence**

``` ruby
<%= ['one', 'two'].to_sentence %>
```

How can this be resolved?
Thank you.

**Comment by berk** [comment]
Thanks for reporting. All those are fixed in the latest gem. Please take a look at the samples here:

https://github.com/translationexchange/tml-rails-samples-welp/blob/master/rails_4.2_i18n/app/views/test/index.html.erb
